import { Restaurant, Menu, MenuItem, Review } from './types';

export const mockRestaurants: Restaurant[] = [
  {
    id: 'rest-1',
    name: 'The Golden Spoon',
    description: 'Fine dining experience with international cuisine',
    address: '123 Main Street, Downtown',
    phone: '+1234567890',
    ownerId: 'owner-1',
    createdAt: new Date('2024-01-01'),
    qrCode: 'rest-1',
  },
];

export const mockMenus: Menu[] = [
  {
    id: 'menu-1',
    restaurantId: 'rest-1',
    name: 'Breakfast Menu',
    description: 'Morning delights to start your day',
    icon: '🍳',
    order: 1,
    isActive: true,
    timeRanges: [{ startTime: '07:00', endTime: '11:00' }],
    createdAt: new Date(),
  },
  {
    id: 'menu-2',
    restaurantId: 'rest-1',
    name: 'All Day Menu',
    description: 'Available all day long',
    icon: '🍽️',
    order: 2,
    isActive: true,
    createdAt: new Date(),
  },
  {
    id: 'menu-3',
    restaurantId: 'rest-1',
    name: 'Dinner Specials',
    description: 'Evening fine dining experience',
    icon: '🌙',
    order: 3,
    isActive: true,
    timeRanges: [{ startTime: '17:00', endTime: '22:00' }],
    createdAt: new Date(),
  },
  {
    id: 'menu-4',
    restaurantId: 'rest-1',
    name: 'Beverages',
    description: 'Refreshing drinks and hot beverages',
    icon: '🍹',
    order: 4,
    isActive: true,
    createdAt: new Date(),
  },
];

export const mockMenuItems: MenuItem[] = [
  {
    id: 'item-1',
    restaurantId: 'rest-1',
    menuId: 'menu-1',
    name: 'Breakfast Pancakes',
    description: 'Fluffy pancakes with maple syrup and fresh berries',
    price: 12.99,
    images: [
      'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=400',
      'https://images.unsplash.com/photo-1528207776546-365bb710ee93?w=400',
    ],
    category: 'Main',
    isAvailable: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'item-2',
    restaurantId: 'rest-1',
    menuId: 'menu-1',
    name: 'Eggs Benedict',
    description: 'Poached eggs with hollandaise sauce on English muffin',
    price: 14.99,
    images: ['https://images.unsplash.com/photo-1608039755401-742074f0548d?w=400'],
    category: 'Main',
    isAvailable: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'item-2b',
    restaurantId: 'rest-1',
    menuId: 'menu-1',
    name: 'French Toast',
    description: 'Thick brioche slices with cinnamon and powdered sugar',
    price: 11.99,
    images: ['https://images.unsplash.com/photo-1484723091739-30a097e8f929?w=400'],
    category: 'Main',
    isAvailable: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'item-2c',
    restaurantId: 'rest-1',
    menuId: 'menu-1',
    name: 'Avocado Toast',
    description: 'Smashed avocado on sourdough with poached eggs',
    price: 13.99,
    images: ['https://images.unsplash.com/photo-1541519227354-08fa5d50c44d?w=400'],
    category: 'Main',
    isAvailable: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'item-2d',
    restaurantId: 'rest-1',
    menuId: 'menu-1',
    name: 'Breakfast Burrito',
    description: 'Scrambled eggs, bacon, cheese, and salsa wrapped in tortilla',
    price: 10.99,
    images: ['https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=400'],
    category: 'Main',
    isAvailable: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'item-2e',
    restaurantId: 'rest-1',
    menuId: 'menu-1',
    name: 'Omelette Special',
    description: 'Three egg omelette with vegetables and cheese',
    price: 12.99,
    images: ['https://images.unsplash.com/photo-1612240498035-913ea4a0f0b0?w=400'],
    category: 'Main',
    isAvailable: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'item-2f',
    restaurantId: 'rest-1',
    menuId: 'menu-1',
    name: 'Bagel & Cream Cheese',
    description: 'Toasted bagel with cream cheese and smoked salmon',
    price: 9.99,
    images: ['https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=400'],
    category: 'Light',
    isAvailable: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'item-2g',
    restaurantId: 'rest-1',
    menuId: 'menu-1',
    name: 'Yogurt Parfait',
    description: 'Greek yogurt layered with granola and fresh berries',
    price: 8.99,
    images: ['https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400'],
    category: 'Light',
    isAvailable: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'item-3',
    restaurantId: 'rest-1',
    menuId: 'menu-2',
    name: 'Classic Burger',
    description: 'Juicy beef patty with lettuce, tomato, and special sauce',
    price: 15.99,
    images: [
      'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400',
      'https://images.unsplash.com/photo-1550547660-d9450f859349?w=400',
    ],
    category: 'Burgers',
    isAvailable: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'item-4',
    restaurantId: 'rest-1',
    menuId: 'menu-2',
    name: 'Caesar Salad',
    description: 'Crisp romaine lettuce with parmesan and croutons',
    price: 10.99,
    images: ['https://images.unsplash.com/photo-1546793665-c74683f339c1?w=400'],
    category: 'Salads',
    isAvailable: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'item-4b',
    restaurantId: 'rest-1',
    menuId: 'menu-2',
    name: 'Chicken Wings',
    description: 'Crispy wings with buffalo or BBQ sauce',
    price: 13.99,
    images: ['https://images.unsplash.com/photo-1608039829572-78524f79c4c7?w=400'],
    category: 'Appetizers',
    isAvailable: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'item-4c',
    restaurantId: 'rest-1',
    menuId: 'menu-2',
    name: 'Fish & Chips',
    description: 'Beer-battered cod with crispy fries',
    price: 16.99,
    images: ['https://images.unsplash.com/photo-1579208575657-c595a05383b7?w=400'],
    category: 'Main',
    isAvailable: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'item-5',
    restaurantId: 'rest-1',
    menuId: 'menu-3',
    name: 'Grilled Salmon',
    description: 'Fresh Atlantic salmon with roasted vegetables and lemon butter',
    price: 24.99,
    images: [
      'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=400',
      'https://images.unsplash.com/photo-1485921325833-c519f76c4927?w=400',
    ],
    category: 'Seafood',
    isAvailable: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'item-6',
    restaurantId: 'rest-1',
    menuId: 'menu-3',
    name: 'Ribeye Steak',
    description: 'Premium aged ribeye with garlic butter and sides',
    price: 32.99,
    images: ['https://images.unsplash.com/photo-1600891964092-4316c288032e?w=400'],
    category: 'Steaks',
    isAvailable: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'item-6b',
    restaurantId: 'rest-1',
    menuId: 'menu-3',
    name: 'Lobster Tail',
    description: 'Butter-poached lobster tail with garlic mashed potatoes',
    price: 38.99,
    images: ['https://images.unsplash.com/photo-1633128607068-a5f2ed0b9f7e?w=400'],
    category: 'Seafood',
    isAvailable: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'item-6c',
    restaurantId: 'rest-1',
    menuId: 'menu-3',
    name: 'Lamb Chops',
    description: 'Herb-crusted lamb chops with mint jelly',
    price: 29.99,
    images: ['https://images.unsplash.com/photo-1595777216528-07c0b06f7c42?w=400'],
    category: 'Main',
    isAvailable: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Beverages Menu Items
  {
    id: 'item-7a',
    restaurantId: 'rest-1',
    menuId: 'menu-4',
    name: 'Fresh Orange Juice',
    description: 'Freshly squeezed orange juice',
    price: 5.99,
    images: ['https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=400'],
    category: 'Fresh Juices',
    isAvailable: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'item-7b',
    restaurantId: 'rest-1',
    menuId: 'menu-4',
    name: 'Mango Smoothie',
    description: 'Tropical mango smoothie with yogurt',
    price: 6.99,
    images: ['https://images.unsplash.com/photo-1505252585461-04db1eb84625?w=400'],
    category: 'Smoothies',
    isAvailable: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'item-7c',
    restaurantId: 'rest-1',
    menuId: 'menu-4',
    name: 'Cappuccino',
    description: 'Classic Italian cappuccino with steamed milk',
    price: 4.99,
    images: ['https://images.unsplash.com/photo-1572442388796-11668a67e53d?w=400'],
    category: 'Coffee',
    isAvailable: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'item-7d',
    restaurantId: 'rest-1',
    menuId: 'menu-4',
    name: 'Iced Latte',
    description: 'Cold espresso with milk over ice',
    price: 5.49,
    images: ['https://images.unsplash.com/photo-1517487881594-2787fef5ebf7?w=400'],
    category: 'Coffee',
    isAvailable: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'item-7e',
    restaurantId: 'rest-1',
    menuId: 'menu-4',
    name: 'Green Tea',
    description: 'Premium Japanese green tea',
    price: 3.99,
    images: ['https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?w=400'],
    category: 'Tea',
    isAvailable: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'item-7f',
    restaurantId: 'rest-1',
    menuId: 'menu-4',
    name: 'Mojito Mocktail',
    description: 'Refreshing mint and lime mocktail',
    price: 7.99,
    images: ['https://images.unsplash.com/photo-1551538827-9c037cb4f32a?w=400'],
    category: 'Mocktails',
    isAvailable: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'item-7g',
    restaurantId: 'rest-1',
    menuId: 'menu-4',
    name: 'Sparkling Water',
    description: 'Chilled sparkling mineral water',
    price: 2.99,
    images: [],
    category: 'Water',
    isAvailable: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'item-7h',
    restaurantId: 'rest-1',
    menuId: 'menu-4',
    name: 'Hot Chocolate',
    description: 'Rich hot chocolate with whipped cream',
    price: 4.49,
    images: ['https://images.unsplash.com/photo-1542990253-0d0f5be5f0ed?w=400'],
    category: 'Hot Beverages',
    isAvailable: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'item-7i',
    restaurantId: 'rest-1',
    menuId: 'menu-4',
    name: 'Lemonade',
    description: 'Classic homemade lemonade',
    price: 4.99,
    images: ['https://images.unsplash.com/photo-1523677011781-c91d1bbe2f9d?w=400'],
    category: 'Soft Drinks',
    isAvailable: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'item-7j',
    restaurantId: 'rest-1',
    menuId: 'menu-4',
    name: 'Iced Tea',
    description: 'Sweetened iced tea with lemon',
    price: 3.99,
    images: ['https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400'],
    category: 'Tea',
    isAvailable: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const mockReviews: Review[] = [];


